# Generated by Django 5.1.3 on 2024-11-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
